### ISSUE TITLE
Bug: Build error when items is an empty object when type array

### ISSUE THREAD

**Issue by Himenon** [Himenon/openapi-typescript-code-generator#12]
## Steps To Reproduce

```yaml
components:
  schemas:
    List:
      type: array
      items: {}
```

[Playground](https://himenon.github.io/openapi-typescript-code-generator-playground/index.html?code=PYBwpgdghiCWBcACAzAOgAyuQKFhAZsPNoogG5gBOAzrMBEgIwYYmIAus7ANmEgCIBRALIB5NgBMw1AMaVYITvSRSAtsETVwMtt1gzI1Pm1LRVfRMICSAFWzYjlCjWKkAtIgCulbkgBEABbs7CDwAPRhUmSoMLCo7NLsqBLAqlB4YX4miFKy8op0DIj8YBTcoOYQ7IiCEGSwlPSV7PYyqSD0kOzUrpoyAWBpPdkAMrDU7L2kpOwAnuBIUJSUULPZpFyDPYgA3gC%2B2EA)

## The current behavior

Build Error

## The expected behavior

```
type List = {}
```
