### ISSUE TITLE
Bug: Infer type if type is not specified

### ISSUE THREAD

**Issue by Himenon** [Himenon/openapi-typescript-code-generator#14]
## Steps To Reproduce

It is below.

## The current behavior

Build Error

## The expected behavior

```yaml
components:
  schemas:
    Item:          # -> type Item =  { description: any }
      required:
        description
```

```yaml
components:
  schemas:
    Items:          # -> type Items =  "a" | "b" | "c";
      enum: [a, b, c]
```

```yaml
components:
  schemas:
    Obj:          # -> type Obj =  "a" | "b" | "c";
      properties:
        filed:
```

```yaml
components:
  schemas:
    Obj:          # -> interface Obj { field: string }
      properties:
        filed:
          type: string
```

```yaml
components:
  schemas:
    List:          # -> type List = string[]
      items:
        type: string
```
