### ISSUE TITLE
Bug:  TS 1214 occured

### ISSUE THREAD

**Issue by Himenon** [Himenon/openapi-typescript-code-generator#43]
## Steps To Reproduce

```yml
components:
  schemas:
    package: // reserved word
      type: object
      properties:
        id:
          type: number
```

## The current behavior

TS Error

```
A software package

Identifier expected. 'package' is a reserved word in strict mode. Modules are automatically in strict mode.ts(1214)
```
