### ISSUE TITLE
BUG: nullable schema

### ISSUE THREAD

**Issue by ssssota** [Himenon/openapi-typescript-code-generator#91]
Hi! I think this project is useful and so interesting.

I have a question. Why do generator use interface for schema definition?

I think type alias is more useful.

e.g.

https://swagger.io/specification/#:~:text=A%20true%20value%20adds%20%22null%22%20to%20the%20allowed%20type%20specified%20by%20the%20type%20keyword%2C%20only%20if%20type%20is%20explicitly%20defined%20within%20the%20same%20Schema%20Object.

```yaml
schema:
  type: object
  nullable: true
  properties:
    foo:
      type: integer
```

```ts
type schema = { foo: number } | null;
```
